# Generated by Django 2.2.1 on 2019-11-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
