# Generated by Django 2.2.1 on 2019-11-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191113_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
